name: custom_tabbarview
description: "Flutter TabBarView, but with enhanced customization capabilities."
version: 0.1.0
repository: https://github.com/wjlee611/custom_tabbarview
issue_tracker: https://github.com/wjlee611/custom_tabbarview/issues
topics: [tabbarview]

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
